"""added action atttribute in reviews

Revision ID: 05c0c212309e
Revises: 
Create Date: 2024-06-19 00:57:08.435598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c0c212309e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.String(length=20), nullable=False))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('action')

    # ### end Alembic commands ###
