"""current_assigned_reviewer unique constraint removed

Revision ID: 55f515ec2439
Revises: 05c0c212309e
Create Date: 2024-06-19 03:22:43.070291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f515ec2439'
down_revision = '05c0c212309e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_assigned_reviewer', sa.Integer(), nullable=True))
        batch_op.drop_column('current_asssigned_reviewer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_asssigned_reviewer', sa.INTEGER(), nullable=True))
        batch_op.drop_column('current_assigned_reviewer')

    # ### end Alembic commands ###
