"""edited reviews table

Revision ID: f613244c1cbc
Revises: fbbd6c85c40d
Create Date: 2024-06-06 17:10:41.519175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f613244c1cbc'
down_revision = 'fbbd6c85c40d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('submission_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_reviews_submission_id', 'submissions', ['submission_id'], ['id'])
        batch_op.create_foreign_key('fk_reviews_event_id', 'event', ['event_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('submission_id')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
